### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pietrafixa** [Sential/WebExpress#11]
I also noticed that you have created WebExpress in different languages. (C #, VB.NET and Electron). Which version to keep doing?

**Comment by Sential** [comment]
Electron

**Comment by Pietrafixa** [comment]
Thank you for your reply. You're very kind. I was curious to know which project you would have continued to develop. I advise you to continue the development of WebExpress in Electron because you are already at a good point. Please excuse my bad english.
